services:
    nest:
        build:
            dockerfile: .docker/nest/Dockerfile
        restart: unless-stopped
        ports:
            - ${NEST_PORT}:3000
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASS: pass
            DB_NAME: postgres
            DB_PORT: 5432

        volumes:
            - ./api:/home/node/app
        depends_on:
            - db

    db:
        image: postgres:16.1-alpine3.19
        restart: always
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: postgres

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        depends_on:
            - db

    angular:
        build:
            dockerfile: .docker/angular/Dockerfile
        container_name: angular
        restart: unless-stopped
        ports:
            - ${NG_PORT}:4200
        volumes:
            - ./frontend:/home/node/app
